apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: demo-app
 template:
  metadata:
   labels:
    app: demo-app
  spec:
   containers: 
    - name: demo-container
      image: harshini123456/demo:latest
      ports:
      - containerPort: 5000
      env:
       - name: ENV
         valueFrom:
          configMapKeyRef:
           name: demo-config
           key: ENV
       - name: PASS
         valueFrom:
          secretKeyRef:
           name: demo-secret
           key: PASS
     
   