apiVersion: apps/v1
kind: Deployment
metadata:
  name: prgm4-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgrm-app
  template:
    metadata:
      labels:
        app: pgrm-app
    spec:
      containers:
        - name: prgm4-container
          image: harshini123456/prgm4-deploy:latest
          ports:
            - containerPort: 5000
